/**
 * Everything that gets posted: the avatar, five cards, and the video frames.
 *
 *   node scripts/build-social.mjs        # writes the HTML
 *   node scripts/render-social.mjs       # drives Chrome and ffmpeg over it
 *
 * ## Why they are generated
 *
 * Every figure on every card is read from `dist/data/index.json` at build time.
 * Nothing here is typed by hand, so a card cannot claim 441 incidents on a day
 * the ledger holds 460 — which is the ordinary way marketing material starts
 * lying about a product without anybody deciding to.
 *
 * It also means the whole set is regenerated by running this again after a
 * pulse, rather than being five files somebody has to remember to redo.
 *
 * ## The series
 *
 * One template, five posts, so the account reads as one voice rather than five
 * unrelated graphics. Each card is a single measured claim: an eyebrow saying
 * which reading it came from, the figure, one sentence, and the domain. No
 * adjectives — the argument is that these numbers can be checked, and a card
 * that opens with "powerful" contradicts it on the first line.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

const bundle = JSON.parse(readFileSync(`${ROOT}dist/data/index.json`, 'utf8'));
const mark = readFileSync(`${ROOT}assets/brand/mark-dark.svg`, 'utf8');

const n = (value) => value.toLocaleString('en');

/** Shared head: the site's own fonts and tokens, so the account cannot drift from the product. */
const HEAD = `<meta charset="utf-8">
<style>
  @font-face { font-family: 'Plex Condensed'; font-weight: 600;
    src: url('../../dist/fonts/ibm-plex-sans-condensed-latin-600-normal.woff2') format('woff2'); }
  @font-face { font-family: 'Plex Mono'; font-weight: 400;
    src: url('../../dist/fonts/ibm-plex-mono-latin-400-normal.woff2') format('woff2'); }
  @font-face { font-family: 'Plex Serif'; font-weight: 400;
    src: url('../../dist/fonts/ibm-plex-serif-latin-400-normal.woff2') format('woff2'); }

  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { background: #121212; color: #e8e8e8; font-family: 'Plex Mono', monospace; overflow: hidden; }

  .eyebrow {
    font-family: 'Plex Condensed', sans-serif; font-weight: 600;
    font-size: 19px; letter-spacing: 0.2em; text-transform: uppercase; color: #9e9e9e;
  }
  /* Tabular figures, always. A column of numbers that shifts as it counts is a
     number nobody trusts, and this is the only thing on the card that matters. */
  .figure {
    font-family: 'Plex Condensed', sans-serif; font-weight: 600;
    font-variant-numeric: tabular-nums; font-size: 168px; line-height: 0.9;
    color: #d2e2f4; letter-spacing: -0.02em;
  }
  .say { font-family: 'Plex Serif', Georgia, serif; font-size: 33px; line-height: 1.45; color: #cfcfcf; }
  .foot {
    position: absolute; left: 76px; right: 76px; bottom: 52px;
    display: flex; justify-content: space-between; align-items: center;
    font-family: 'Plex Condensed', sans-serif; font-weight: 600;
    font-size: 17px; letter-spacing: 0.18em; text-transform: uppercase; color: #6b6b6b;
  }
  .foot .mark { display: flex; align-items: center; gap: 14px; color: #9e9e9e; }
</style>`;

/** 1200x675. The 16:9 that X shows uncropped in a timeline. */
function card({ eyebrow, figure, unit, say }) {
  return `<!doctype html><html lang="en"><head>${HEAD}
<style>
  body { width: 1200px; height: 675px; position: relative; }
  .frame { position: absolute; inset: 0; padding: 74px 76px 0; display: flex;
           flex-direction: column; justify-content: center; gap: 26px; padding-bottom: 130px; }
  .unit { font-family: 'Plex Condensed', sans-serif; font-weight: 600; font-size: 27px;
          letter-spacing: 0.13em; text-transform: uppercase; color: #9e9e9e; margin-top: 4px; }
  .say { max-width: 30ch; }
</style></head>
<body>
  <div class="frame">
    <span class="eyebrow">${eyebrow}</span>
    <div>
      <div class="figure">${figure}</div>
      <div class="unit">${unit}</div>
    </div>
    <p class="say">${say}</p>
  </div>
  <div class="foot">
    <span class="mark">${mark.replace('width="64" height="64"', 'width="30" height="30"')} Sighttrue</span>
    <span>sighttrue.com</span>
  </div>
</body></html>`;
}

/**
 * Five cards, in posting order.
 *
 * The first three are readings that have nothing to do with GitHub, deliberately.
 * "A GitHub summariser" is the fair objection to this product and the fastest
 * way to answer it is to lead with three things GitHub does not know.
 */
const CARDS = [
  {
    file: 'post-1-incidents',
    eyebrow: 'Outages · kept after the feeds forget',
    figure: n(bundle.incidents.total),
    unit: `incidents across ${bundle.incidents.providers} providers`,
    say: 'Status pages drop their history. Ask how often your cloud provider failed last year and nobody has the record. This one does.',
  },
  {
    file: 'post-2-eol',
    eyebrow: 'End of life · published years ahead',
    figure: n(bundle.lifecycle.dated),
    unit: `release lines on the clock`,
    say: 'The dates are announced early and watched by almost nobody. Most teams learn their runtime went unsupported when an auditor tells them.',
  },
  {
    file: 'post-3-busfactor',
    eyebrow: 'Bus factor · read from commit history',
    figure: n(bundle.contributors.measured),
    unit: 'projects, by who actually writes them',
    say: 'Every health signal measures activity. None of them measures how many people a project would survive losing.',
  },
  {
    file: 'post-4-staleness',
    eyebrow: 'Shipped · from the registry, not the repo',
    figure: n(bundle.staleness.measured),
    unit: 'packages, by real release date',
    say: 'A green commit graph is what a maintainer does for themselves. A release is what reaches you. They are not the same date.',
  },
  {
    file: 'post-5-yourstack',
    eyebrow: 'Your stack · no account, nothing installed',
    figure: n(bundle.adoption.measured),
    unit: 'packages already measured',
    say: 'Paste a package.json, requirements.txt or Cargo.toml. Every dependency is checked for advisories, and it never leaves your browser.',
  },
];

for (const entry of CARDS) {
  writeFileSync(`${ROOT}assets/brand/${entry.file}.html`, card(entry), 'utf8');
}

/**
 * The video, as one page that draws any frame it is asked for.
 *
 * `?f=N` rather than a CSS animation left to run. A screenshot of a playing
 * animation lands wherever the renderer happened to be, so the same command
 * twice gives two different films. Every value here is computed from the frame
 * number, which makes the whole thing reproducible and lets a bad second be
 * re-rendered on its own.
 */
const FPS = 30;
const SECONDS = 8;

const film = `<!doctype html><html lang="en"><head>${HEAD}
<style>
  body { width: 1200px; height: 675px; position: relative; }
  .stage { position: absolute; inset: 0; display: grid; place-items: center; }
  .lockup { display: flex; align-items: center; gap: 30px; }
  .word { font-family: 'Plex Condensed', sans-serif; font-weight: 600; font-size: 92px;
          letter-spacing: -0.015em; line-height: 1; }
  .line { font-family: 'Plex Serif', Georgia, serif; font-size: 34px; color: #cfcfcf;
          text-align: center; max-width: 26ch; }
  .rows { display: grid; gap: 22px; width: 660px; }
  .row { display: flex; justify-content: space-between; align-items: baseline;
         border-bottom: 1px solid #2c2c2c; padding-bottom: 12px; }
  .row span { font-family: 'Plex Condensed', sans-serif; font-weight: 600; font-size: 21px;
              letter-spacing: 0.14em; text-transform: uppercase; color: #9e9e9e; }
  .row b { font-weight: 400; font-size: 46px; font-variant-numeric: tabular-nums; color: #d2e2f4; }
  .url { font-family: 'Plex Condensed', sans-serif; font-weight: 600; font-size: 30px;
         letter-spacing: 0.2em; text-transform: uppercase; color: #9e9e9e; }
  .col { display: grid; gap: 40px; place-items: center; }
</style></head>
<body>
  <div class="stage" id="stage"></div>
<script>
  const FPS = ${FPS};
  const frame = Number(new URLSearchParams(location.search).get('f') || 0);
  const t = frame / FPS;

  // Ease-out. Motion that decelerates reads as something settling into place;
  // linear motion reads as a slide, which is decoration.
  const ease = (x) => 1 - Math.pow(1 - Math.min(1, Math.max(0, x)), 3);
  const window_ = (from, to) => ease((t - from) / (to - from));

  const FIGURES = ${JSON.stringify([
    ['Repositories', bundle.watchlist.active],
    ['Incidents kept', bundle.incidents.total],
    ['EOL clocks', bundle.lifecycle.dated],
    ['Commit histories', bundle.contributors.measured],
  ])};

  const mark = ${JSON.stringify(mark.replace('width="64" height="64"', 'width="104" height="104"'))};
  const stage = document.getElementById('stage');

  if (t < 2.6) {
    // The name, arriving.
    const p = window_(0.2, 1.4);
    stage.innerHTML =
      '<div class="lockup" style="opacity:' + p + ';transform:translateY(' + (18 - 18 * p) + 'px)">' +
      mark + '<span class="word">Sighttrue</span></div>';
  } else if (t < 5.4) {
    // The figures, counting. Counting rather than appearing, because the claim
    // is that these are measured — and a number that ticks up reads as a
    // reading being taken rather than a badge being placed.
    const p = window_(2.7, 4.6);
    stage.innerHTML = '<div class="rows">' + FIGURES.map((row, i) => {
      const own = ease((t - 2.7 - i * 0.18) / 1.5);
      const value = Math.round(row[1] * own).toLocaleString('en');
      return '<div class="row" style="opacity:' + Math.min(1, own * 1.6) + '">' +
        '<span>' + row[0] + '</span><b>' + value + '</b></div>';
    }).join('') + '</div>';
    stage.style.opacity = String(t > 5.1 ? 1 - (t - 5.1) / 0.3 : 1);
  } else {
    const p = window_(5.5, 6.6);
    stage.innerHTML =
      '<div class="col" style="opacity:' + p + '">' +
      mark +
      '<p class="line">Take the reading, and check it.</p>' +
      '<span class="url">sighttrue.com</span></div>';
  }
</script>
</body></html>`;

writeFileSync(`${ROOT}assets/brand/film.html`, film, 'utf8');

/** The avatar. One mark, nothing else: the only size that matters is 48px. */
writeFileSync(
  `${ROOT}assets/brand/avatar.html`,
  `<!doctype html><meta charset="utf-8">
<style>html,body{margin:0;padding:0}
body{width:400px;height:400px;background:#121212;display:grid;place-items:center}</style>
${mark.replace('width="64" height="64"', 'width="312" height="312"')}`,
  'utf8',
);

console.log(`${CARDS.length} cards, film.html (${SECONDS}s at ${FPS}fps) and avatar.html written`);
console.log(`frames to render: ${SECONDS * FPS}`);
