/**
 * The mark: a lens sighting down onto a datum.
 *
 *   node scripts/build-mark.mjs
 *
 * ## The rules, taken from the reference
 *
 * Eight marks were drawn and rejected before this one. The user then supplied a
 * logofolio of about eighty marks, and it settles the question of *how* a mark
 * for this project has to be built, whatever it depicts:
 *
 *   1. Solid fill. No outlines, no stroke weights to get wrong.
 *   2. Heavy. Every mark in that sheet survives being printed at the size of a
 *      fingernail.
 *   3. One flat colour, with nothing depending on a second.
 *   4. Negative space does a job. The counter is where the second reading
 *      lives, and it is what separates a logo from a pictogram.
 *
 * Every one of the first six failures was the same defect: thin. Hairlines and
 * outlines, defensible on paper and unfinished on screen.
 *
 * ## What it depicts, and what it deliberately is not
 *
 * A lens — the vesica every optical element makes — with the pupil punched out
 * of it, sighting down at the line it is measured against. Sight, and true.
 *
 * The two most recent failures were not drawing errors. They were collisions:
 * a solid round-capped bob is the Google Maps pin, and the same shape with a
 * collar on a cord is a crucifix. So the test applied here before anything was
 * drawn was not "is this a good shape" but "what does this shape already mean
 * to somebody who has never heard of us".
 *
 * A pointed oval with a hole in it is a lens, an eye and an aperture, and none
 * of those three is the wrong answer for a product called Sighttrue. It is not
 * a pin, a cross, a target, a clock or a letter.
 *
 * The counter is large on purpose: a small hole closes up at 16px and the
 * second reading disappears exactly where a mark most needs to be legible. It
 * has to stay inside the lens, though — see BOW, where getting that wrong once
 * produced a pupil hanging out of the bottom of the eye.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

/** The lens. Wide and shallow, the way a real optical element is drawn. */
const LEFT = 5;
const RIGHT = 59;
const MID_Y = 27;
/**
 * How far the two arcs bow.
 *
 * A quadratic reaches only half its control offset, so this is double the
 * height the lens actually gets: 30 here means the shape spans 15 units either
 * side of the midline. That caught me out — at 20 the lens was 20 units tall
 * and held a pupil 19 across, so the counter burst through the bottom edge and
 * the mark looked broken rather than drawn.
 *
 * Fat regardless, which is the one property the reference demands without
 * exception.
 */
const BOW = 30;

/**
 * The pupil.
 *
 * Below centre, not on it. Centred, the mark is a symmetrical eye staring
 * outward — which reads as surveillance, and is the wrong feeling entirely for
 * something whose promise is that you can check its work. Dropped a few units,
 * the lens is looking down at the line beneath it, which is what taking a
 * reading looks like.
 */
const PUPIL = { y: 28.5, r: 8.2 };

/** The reference the lens is sighted against. */
const DATUM = { y: 55, h: 4, inset: 12 };

const r = (n) => Number(n.toFixed(2));

/**
 * Lens and pupil as one path, with `evenodd` cutting the hole.
 *
 * One path rather than a shape with a background-coloured circle on top. A
 * painted counter stops being a hole the moment the mark is placed on anything
 * else — a sticker, somebody's slide, a dark timeline — and that is the most
 * common way a logo breaks once it leaves the file it was drawn in.
 */
const LENS = [
  `M ${LEFT} ${MID_Y}`,
  `Q 32 ${r(MID_Y - BOW)} ${RIGHT} ${MID_Y}`,
  `Q 32 ${r(MID_Y + BOW)} ${LEFT} ${MID_Y}`,
  'Z',
  `M 32 ${r(PUPIL.y - PUPIL.r)}`,
  `a ${PUPIL.r} ${PUPIL.r} 0 1 0 0.01 0`,
  'Z',
].join(' ');

function mark({ ink, alert, title, datum = true }) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64" role="img" aria-label="${title}">
  <title>${title}</title>

  <!--
    A lens sighting down onto its datum. Generated by scripts/build-mark.mjs,
    which records the eight marks this replaced and the rule taken from the
    reference: solid, heavy, one colour, and the counter carrying the second
    reading.

    The pupil sits below centre. Centred, this is a symmetrical eye staring out,
    which reads as surveillance — the wrong feeling for a product whose promise
    is that you can check its work.
  -->

  <path d="${LENS}" fill="${ink}" fill-rule="evenodd" />
${
  datum
    ? `
  <!-- The line the reading is taken against. The only element carrying a
       judgement, so the only one in the alert colour. -->
  <rect x="${DATUM.inset}" y="${DATUM.y}" width="${r(64 - DATUM.inset * 2)}" height="${DATUM.h}" fill="${alert}" />`
    : ''
}
</svg>
`;
}

writeFileSync(
  `${ROOT}assets/brand/mark.svg`,
  mark({ ink: 'currentColor', alert: 'currentColor', title: 'Sighttrue' }),
  'utf8',
);

/**
 * The favicon and the avatar carry their own colours. Neither inherits anything
 * from a page, and both are drawn against chrome this project does not control.
 */
writeFileSync(
  `${ROOT}src/site/favicon.svg`,
  mark({ ink: '#d2e2f4', alert: '#f2857c', title: 'Sighttrue' }),
  'utf8',
);

writeFileSync(
  `${ROOT}assets/brand/mark-dark.svg`,
  mark({ ink: '#d2e2f4', alert: '#f2857c', title: 'Sighttrue' }),
  'utf8',
);

writeFileSync(
  `${ROOT}assets/brand/mark-light.svg`,
  mark({ ink: '#1a1a1a', alert: '#a3231b', title: 'Sighttrue' }),
  'utf8',
);

/** Silhouette only, for the avatar and anywhere the datum would crowd it. */
writeFileSync(
  `${ROOT}assets/brand/mark-solo.svg`,
  mark({ ink: '#d2e2f4', alert: '#f2857c', title: 'Sighttrue', datum: false }),
  'utf8',
);

console.log('mark.svg, mark-dark.svg, mark-light.svg, mark-solo.svg and favicon.svg written');
