/**
 * Generate the banner from the site's own readings.
 *
 *   node scripts/build-brand.mjs
 *
 * The velocity strip is the one image this project has that nobody else could
 * produce, because it is drawn from four hundred repositories measured against
 * their own baselines rather than from a design tool. Faking it with a nice
 * looking waveform would throw away the only thing that makes the banner worth
 * having.
 *
 * So the strip is lifted out of the built homepage rather than redrawn. If the
 * site has not been built, this refuses rather than inventing one.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
// The instrument, not the front door. `/` became a welcome page and the strip
// moved with the instrument to `/live`; this script went on reading `/` and
// refused to build, which is the guard working — it would rather stop than
// invent a strip.
const INDEX = `${ROOT}dist/live.html`;
const OUT = `${ROOT}assets/brand/banner.html`;

if (!existsSync(INDEX)) {
  console.error('dist/live.html is missing. Run `node scripts/build.ts` first.');
  process.exit(1);
}

const page = readFileSync(INDEX, 'utf8');

/** The strip, exactly as the site draws it. */
const raw = /<svg viewBox="0 0 100 100"[\s\S]*?<\/svg>/.exec(page)?.[0];
if (raw === undefined) {
  console.error('No velocity strip in the built page. The banner is not worth making without it.');
  process.exit(1);
}

const bundle = JSON.parse(readFileSync(`${ROOT}dist/data/index.json`, 'utf8'));
const watched = bundle.watchlist.active;

const mark = readFileSync(`${ROOT}assets/brand/mark-dark.svg`, 'utf8')
  .replace('width="64" height="64"', 'width="132" height="132"');

const incidents = bundle.incidents.total.toLocaleString('en');
const eol = bundle.lifecycle.dated;
const packages = bundle.adoption.measured;

const banner = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Sighttrue banner</title>
<!--
  GENERATED by scripts/build-brand.mjs. Do not edit by hand.

  One sentence, not a stat sheet. The previous banner led with four figures and
  read as a summary of somebody else's GitHub — which is exactly the objection
  this product has to answer, printed across the top of the profile.

  A header gets three seconds. A sentence that makes a developer think "wait,
  that is true of my project" beats four numbers they have no context for.

  Laid out for what X does to a header: the avatar covers the bottom-left, so
  nothing that must be read goes there, and mobile crops to the middle band.
-->
<style>
  @font-face { font-family: 'Plex Condensed'; font-weight: 600;
    src: url('../../dist/fonts/ibm-plex-sans-condensed-latin-600-normal.woff2') format('woff2'); }
  @font-face { font-family: 'Plex Mono'; font-weight: 400;
    src: url('../../dist/fonts/ibm-plex-mono-latin-400-normal.woff2') format('woff2'); }
  @font-face { font-family: 'Plex Serif'; font-weight: 400;
    src: url('../../dist/fonts/ibm-plex-serif-latin-400-normal.woff2') format('woff2'); }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { width: 1500px; height: 500px; background: #121212; color: #e8e8e8;
         font-family: 'Plex Mono', monospace; overflow: hidden; position: relative; }
  .frame { position: absolute; inset: 0; padding: 74px 82px 0;
           display: flex; flex-direction: column; justify-content: center; padding-bottom: 96px; }
  .say { font-family: 'Plex Serif', Georgia, serif; font-size: 62px; line-height: 1.24;
         letter-spacing: -0.014em; max-width: 21ch; }
  .say b { font-weight: 400; color: #d2e2f4; }
  .lockup { position: absolute; right: 82px; bottom: 96px; display: flex;
            align-items: center; gap: 18px; }
  .wm { font-family: 'Plex Condensed', sans-serif; font-weight: 600; font-size: 46px;
        letter-spacing: -0.022em; line-height: 1; text-transform: none; }
  .foot { position: absolute; left: 82px; right: 82px; bottom: 42px;
          display: flex; justify-content: space-between;
          font-family: 'Plex Condensed', sans-serif; font-weight: 600; font-size: 16px;
          letter-spacing: 0.18em; text-transform: uppercase; color: #6b6b6b; }
</style></head>
<body>
  <div class="frame">
    <p class="say">A dependency you already ship changed its licence, and
    <b>nobody told you.</b></p>
  </div>
  <div class="lockup">
    ${mark.replace('width="64" height="64"', 'width="72" height="72"')}
    <span class="wm">sighttrue</span>
  </div>
  <div class="foot">
    <span>sighttrue.com &middot; @Sighttruehq</span>
    <!-- No repository count. It was here in the footer while the headline was
         being rewritten to stop sounding like a GitHub summary, which made the
         rewrite pointless — a reader takes the whole image at once. Cadence is
         a promise about the product; a repo count is a fact about our backlog,
         and nobody outside this project has a reason to care about it. -->
    <span>read every 4 hours</span>
  </div>
</body></html>
`;

writeFileSync(OUT, banner);
console.log(`banner.html written from the real strip across ${watched} repositories.`);
