/**
 * Generate the banner from the site's own readings.
 *
 *   node scripts/build-brand.mjs
 *
 * The velocity strip is the one image this project has that nobody else could
 * produce, because it is drawn from four hundred repositories measured against
 * their own baselines rather than from a design tool. Faking it with a nice
 * looking waveform would throw away the only thing that makes the banner worth
 * having.
 *
 * So the strip is lifted out of the built homepage rather than redrawn. If the
 * site has not been built, this refuses rather than inventing one.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const INDEX = `${ROOT}dist/index.html`;
const OUT = `${ROOT}assets/brand/banner.html`;

if (!existsSync(INDEX)) {
  console.error('dist/index.html is missing. Run `node scripts/build.ts` first.');
  process.exit(1);
}

const page = readFileSync(INDEX, 'utf8');

/** The strip, exactly as the site draws it. */
const raw = /<svg viewBox="0 0 100 100"[\s\S]*?<\/svg>/.exec(page)?.[0];
if (raw === undefined) {
  console.error('No velocity strip in the built page. The banner is not worth making without it.');
  process.exit(1);
}

const bundle = JSON.parse(readFileSync(`${ROOT}dist/data/index.json`, 'utf8'));
const watched = bundle.watchlist.active;

const banner = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Sighttrue banner</title>
<!--
  GENERATED by scripts/build-brand.mjs. Do not edit by hand.

  The strip below is lifted from the built homepage, so it is the real reading
  from ${watched} repositories rather than a drawing of one. Regenerate after a
  build; see assets/brand/README.md for the render command.
-->
<style>
  @font-face {
    font-family: 'Plex Condensed';
    src: url('../../dist/fonts/ibm-plex-sans-condensed-latin-600-normal.woff2') format('woff2');
    font-weight: 600;
  }
  @font-face {
    font-family: 'Plex Mono';
    src: url('../../dist/fonts/ibm-plex-mono-latin-400-normal.woff2') format('woff2');
    font-weight: 400;
  }

  * { margin: 0; padding: 0; box-sizing: border-box; }

  body {
    width: 1500px;
    height: 500px;
    background: #0a0d07;
    color: #e9ecdf;
    font-family: 'Plex Mono', monospace;
    overflow: hidden;
    position: relative;
  }

  /* Faint graticule, the same one behind the avatar. */
  body::before {
    content: '';
    position: absolute;
    inset: 0;
    background:
      linear-gradient(#1d2317 1px, transparent 1px) 0 0 / 100% 60px,
      linear-gradient(90deg, #1d2317 1px, transparent 1px) 0 0 / 60px 100%;
  }

  .plate {
    position: relative;
    height: 100%;
    /* X overlays the avatar bottom-left and crops differently on mobile.
       Nothing that must be read goes in the lower-left 300x200. */
    padding: 74px 90px 90px 90px;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
  }

  .head { display: flex; align-items: center; gap: 26px; }

  .mark { width: 76px; height: 76px; flex: none; }

  .wordmark {
    font-family: 'Plex Condensed', sans-serif;
    font-weight: 600;
    font-size: 62px;
    letter-spacing: 0.2em;
    text-transform: uppercase;
    line-height: 1;
  }

  .line {
    font-size: 25px;
    color: #c4cab8;
    margin-top: 18px;
    letter-spacing: 0.01em;
  }

  /* The strip, at banner scale. The stroke is heavier than on the site: at
     130px tall a 0.06 stroke in a 100-unit viewBox is sub-pixel and the comb
     vanishes into a hairline. Same data, drawn thick enough to read.

     Was: /* The strip, at banner scale. Its own stylesheet is not loaded here, so the
     few properties it needs are restated rather than guessed at. */
  .strip { width: 100%; height: 118px; display: block; }
  .strip .mark-bar { fill: #5c7a00; }
  .strip .mark-forming { fill: none; stroke: #7f8a70; stroke-width: 0.09; }
  .strip .mark-detected,
  .strip .mark-confirmed { fill: #ccff00; }
  .strip .baseline-rule { stroke: #3a4230; stroke-width: 0.4; }
  .strip .released { fill: #38bdf8; }

  .caption {
    font-size: 17px;
    color: #5c6450;
    margin-top: 14px;
    letter-spacing: 0.02em;
  }

  .foot {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    font-size: 20px;
    color: #929a86;
    letter-spacing: 0.05em;
  }

  .foot strong { color: #ccff00; font-weight: 400; }
</style>
</head>
<body>
  <div class="plate">
    <div>
      <div class="head">
        <svg class="mark" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg">
          <g fill="none" stroke="#ccff00" stroke-width="3.5" stroke-linecap="square">
            <path d="M26 6 V58" />
            <path d="M4 26 H14" />
            <path d="M38 26 H60" />
            <circle cx="26" cy="26" r="12" />
          </g>
          <circle cx="26" cy="26" r="3" fill="#ccff00" />
        </svg>
        <span class="wordmark">Sighttrue</span>
      </div>
      <p class="line">Watches your dependencies and tells you when one goes bad.</p>
    </div>

    ${raw.replace('<svg ', '<svg class="strip" ')}

    <p class="caption">Every watched repository, against its own baseline. Flat is the instrument at rest.</p>

    <div class="foot">
      <span><strong>${watched}</strong> repositories &middot; read every 4 hours</span>
      <span>sighttrue.com</span>
    </div>
  </div>
</body>
</html>
`;

writeFileSync(OUT, banner);
console.log(`banner.html written from the real strip across ${watched} repositories.`);
