/**
 * The mark.
 *
 *   node scripts/build-mark.mjs
 *
 * A geometric S sitting on a datum line.
 *
 * ## How it got here
 *
 * Three rejected marks, each one instructive, and the record is kept because
 * the reasons are the brief.
 *
 * **Crosshairs.** The icon every monitoring product and half the shooting
 * ranges already use. It said "we look at things", which is not a claim, and at
 * 48 pixels it was a plus sign in a circle.
 *
 * **A graduated dial.** Thirty-six thin ticks inside a ring. It carried the
 * meaning exactly and read as a wristwatch — fine hairlines on a circle is a
 * watch face, and irregular tick lengths do not overcome that at a glance,
 * which is the only look a mark gets.
 *
 * **An aperture.** Six solid blades, one closed further. Bold enough, held at
 * 16px, and still an abstract icon: it needed a paragraph to explain, and a
 * mark that needs explaining is doing the wordmark's job badly.
 *
 * ## Why a letterform
 *
 * The name is the asset. An abstract instrument icon has to earn recognition
 * from nothing; a letter arrives already carrying it, and after three attempts
 * at abstraction that is the honest conclusion.
 *
 * Two arcs, one grid, no tapering and no optical corrections beyond the
 * overshoot below — geometric rather than drawn, because the rest of this
 * product is a measuring instrument and a hand-lettered S would be the only
 * thing in it pretending to be made by hand.
 *
 * ## The datum
 *
 * Two short rules either side of the letter, at its waist, in the alert colour.
 * That is the whole of the meaning and it is worth the two lines: a reference
 * the letter is measured against, which is the "true" in the name.
 *
 * They stop short of the S rather than crossing it. A line through a letter is
 * a strikethrough, and a mark that reads as its own name crossed out is a
 * failure of a specific and embarrassing kind.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

/** Stroke of the letter. Heavy: weight is what reads as considered at any size. */
const W = 9;

/** The two bowls. Equal radii, stacked, meeting at the waist. */
const R = 10.5;
const TOP = { x: 32, y: 21.5 };
const BOTTOM = { x: 32, y: 42.5 };

/**
 * Where each bowl's stroke ends, measured from the horizontal.
 *
 * Six degrees, so the terminals are cut very nearly vertical — the classic
 * geometric cut, and the only one that stays clean here.
 *
 * It was 42 first, which put the terminal only 48 degrees from where the same
 * bowl ends at the waist. At this stroke weight the two overlapped and left a
 * wedge poking into the counter, which reads as a drawing error rather than a
 * letter. The fix is distance, not a smaller stroke: the bowl sweeps nearly a
 * full turn and its two ends have to be far enough apart to stay apart.
 */
const TERMINAL = 6;

const rad = (deg) => (deg * Math.PI) / 180;
const round = (n) => Number(n.toFixed(2));
const on = (c, deg, r = R) =>
  `${round(c.x + Math.cos(rad(deg)) * r)} ${round(c.y + Math.sin(rad(deg)) * r)}`;

/**
 * The letter, as one path.
 *
 * Upper bowl swept anticlockwise from its lower-right terminal all the way
 * round to the waist; lower bowl clockwise from the waist round to its
 * upper-left terminal. Two arcs, one continuous stroke, no join to align.
 */
const S = [
  `M ${on(TOP, TERMINAL)}`,
  `A ${R} ${R} 0 1 0 ${on(TOP, 90)}`,
  `A ${R} ${R} 0 1 1 ${on(BOTTOM, 180 - TERMINAL)}`,
].join(' ');

/** The waist, where the datum sits. */
const WAIST = 32;
/** How far the rules stop short of the letter. Enough to read as a gap at 32px. */
const CLEAR = 4;

function mark({ ink, alert, title }) {
  const left = `M 2 ${WAIST} H ${round(TOP.x - R - W / 2 - CLEAR)}`;
  const right = `M ${round(TOP.x + R + W / 2 + CLEAR)} ${WAIST} H 62`;

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64" role="img" aria-label="${title}">
  <title>${title}</title>

  <!--
    A geometric S on a datum line. Generated by scripts/build-mark.mjs, which
    records the three marks this replaced and why each failed.

    The rules either side are the reference the letter is measured against — the
    "true" in the name. They stop short of the S rather than crossing it,
    because a line through a letter is a strikethrough and a mark that reads as
    its own name crossed out fails in a specific and embarrassing way.
  -->

  <path d="${S}" fill="none" stroke="${ink}" stroke-width="${W}" stroke-linecap="butt" />

  <g stroke="${alert}" stroke-width="3.4" stroke-linecap="butt">
    <path d="${left}" />
    <path d="${right}" />
  </g>
</svg>
`;
}

writeFileSync(
  `${ROOT}assets/brand/mark.svg`,
  mark({ ink: 'currentColor', alert: 'currentColor', title: 'Sighttrue' }),
  'utf8',
);

/**
 * The tab icon carries its own colours: a favicon is drawn against whatever
 * chrome the browser has and can inherit nothing.
 */
writeFileSync(
  `${ROOT}src/site/favicon.svg`,
  mark({ ink: '#d2e2f4', alert: '#f2857c', title: 'Sighttrue' }),
  'utf8',
);

writeFileSync(
  `${ROOT}assets/brand/mark-dark.svg`,
  mark({ ink: '#d2e2f4', alert: '#f2857c', title: 'Sighttrue' }),
  'utf8',
);

writeFileSync(
  `${ROOT}assets/brand/mark-light.svg`,
  mark({ ink: '#1a1a1a', alert: '#a3231b', title: 'Sighttrue' }),
  'utf8',
);

console.log('mark.svg, mark-dark.svg, mark-light.svg and favicon.svg written');
