/**
 * Generate the banner from the site's own readings.
 *
 *   node scripts/build-brand.mjs
 *
 * The velocity strip is the one image this project has that nobody else could
 * produce, because it is drawn from four hundred repositories measured against
 * their own baselines rather than from a design tool. Faking it with a nice
 * looking waveform would throw away the only thing that makes the banner worth
 * having.
 *
 * So the strip is lifted out of the built homepage rather than redrawn. If the
 * site has not been built, this refuses rather than inventing one.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
// The instrument, not the front door. `/` became a welcome page and the strip
// moved with the instrument to `/live`; this script went on reading `/` and
// refused to build, which is the guard working — it would rather stop than
// invent a strip.
const INDEX = `${ROOT}dist/live.html`;
const OUT = `${ROOT}assets/brand/banner.html`;

if (!existsSync(INDEX)) {
  console.error('dist/live.html is missing. Run `node scripts/build.ts` first.');
  process.exit(1);
}

const page = readFileSync(INDEX, 'utf8');

/** The strip, exactly as the site draws it. */
const raw = /<svg viewBox="0 0 100 100"[\s\S]*?<\/svg>/.exec(page)?.[0];
if (raw === undefined) {
  console.error('No velocity strip in the built page. The banner is not worth making without it.');
  process.exit(1);
}

const bundle = JSON.parse(readFileSync(`${ROOT}dist/data/index.json`, 'utf8'));
const watched = bundle.watchlist.active;

const mark = readFileSync(`${ROOT}assets/brand/mark-dark.svg`, 'utf8')
  .replace('width="64" height="64"', 'width="132" height="132"');

const incidents = bundle.incidents.total.toLocaleString('en');
const eol = bundle.lifecycle.dated;
const packages = bundle.adoption.measured;

const banner = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Sighttrue banner</title>
<!--
  GENERATED by scripts/build-brand.mjs. Do not edit by hand.

  The strip along the bottom is lifted from the built homepage, so it is the
  real reading from ${watched} repositories rather than a drawing of one. That is
  the only thing on here nobody else could produce, which is why it is here and
  why faking it would defeat the point.

  Laid out for what X actually does to a header. The avatar lands on the
  bottom-left, so nothing that has to be read goes there. Mobile crops to the
  middle band, so the mark, the name and the sentence all sit inside it.
-->
<style>
  @font-face {
    font-family: 'Plex Condensed';
    src: url('../../dist/fonts/ibm-plex-sans-condensed-latin-600-normal.woff2') format('woff2');
    font-weight: 600;
  }
  @font-face {
    font-family: 'Plex Serif';
    src: url('../../dist/fonts/ibm-plex-serif-latin-400-normal.woff2') format('woff2');
    font-weight: 400;
  }
  @font-face {
    font-family: 'Plex Mono';
    src: url('../../dist/fonts/ibm-plex-mono-latin-400-normal.woff2') format('woff2');
    font-weight: 400;
  }

  * { margin: 0; padding: 0; box-sizing: border-box; }

  body {
    width: 1500px;
    height: 500px;
    background: #121212;
    color: #e8e8e8;
    font-family: 'Plex Mono', monospace;
    overflow: hidden;
    position: relative;
  }

  .frame {
    position: absolute;
    inset: 0;
    padding: 58px 78px 0;
    display: flex;
    flex-direction: column;
  }

  /* Two columns. The sentence was running to 58ch across a 1500px canvas and
     leaving the right 40 per cent empty, which reads as an unfinished layout
     rather than as restraint. */
  .split { display: flex; gap: 90px; align-items: flex-start; margin-top: 30px; }

  .lockup { display: flex; align-items: center; gap: 30px; }

  .wordmark {
    font-family: 'Plex Condensed', sans-serif;
    font-weight: 600;
    font-size: 78px;
    letter-spacing: -0.015em;
    line-height: 1;
  }

  /* Set in the prose face rather than the mono. Mono at 25px across three lines
     reads as a terminal transcript, and this sentence is the one piece of
     writing on the image — it should look like writing. */
  .line {
    font-family: 'Plex Serif', Georgia, serif;
    font-size: 27px;
    line-height: 1.5;
    color: #cfcfcf;
    max-width: 30ch;
    flex: 0 0 auto;
  }

  /* Figures, not adjectives. Every one of them is on the site and checkable,
     which is the entire pitch and so the only thing worth the space. */
  .figures {
    display: grid;
    grid-template-columns: repeat(2, auto);
    gap: 30px 76px;
  }
  .figure { display: flex; flex-direction: column; gap: 5px; }
  .figure b {
    font-weight: 400;
    font-size: 40px;
    font-variant-numeric: tabular-nums;
    color: #d2e2f4;
    line-height: 1;
  }
  .figure span {
    font-family: 'Plex Condensed', sans-serif;
    font-weight: 600;
    font-size: 14px;
    letter-spacing: 0.16em;
    text-transform: uppercase;
    color: #9e9e9e;
  }

  /* The strip runs the full width, bled to both edges, because it is a
     continuous reading and a margin around it would make it a picture of one. */
  /* Full-bleed along the very bottom edge, under everything, so it can never
     cut through a label again — it did, and the figures were unreadable. */
  .strip {
    position: absolute;
    left: 0;
    right: 0;
    bottom: 0;
    width: 1500px;
    height: 62px;
    display: block;
    opacity: 0.85;
  }

  /* Says what the flat line means. Every baseline is still forming, so the
     strip genuinely has nothing to report — and a caption turns that from a
     graphic that looks broken into the instrument saying so. Without it this
     would be a decorative texture bar, which is the one thing the design rules
     for this product forbid outright. */
  .caption {
    position: absolute;
    right: 78px;
    bottom: 76px;
    font-family: 'Plex Condensed', sans-serif;
    font-weight: 600;
    font-size: 15px;
    letter-spacing: 0.14em;
    text-transform: uppercase;
    color: #6b6b6b;
    text-align: right;
  }

  .foot {
    position: absolute;
    left: 78px;
    right: 78px;
    bottom: 76px;
    display: flex;
    justify-content: space-between;
    font-family: 'Plex Condensed', sans-serif;
    font-weight: 600;
    font-size: 15px;
    letter-spacing: 0.16em;
    text-transform: uppercase;
    color: #6b6b6b;
  }
</style>
</head>
<body>
  <div class="frame">
    <div class="lockup">
      ${mark}
      <span class="wordmark">Sighttrue</span>
    </div>

    <div class="split">
      <p class="line">Take the reading, and check it. Every figure here is published as
      a file and committed.</p>

      <div class="figures">
      <div class="figure"><b>${watched}</b><span>Repositories</span></div>
      <div class="figure"><b>${incidents}</b><span>Incidents kept</span></div>
      <div class="figure"><b>${eol}</b><span>EOL clocks</span></div>
        <div class="figure"><b>${packages}</b><span>Packages</span></div>
      </div>
    </div>
  </div>

  ${raw.replace('<svg ', '<svg class="strip" ')}

  <p class="caption">Every watched repository, against its own baseline &mdash; flat is the instrument at rest</p>

  <div class="foot">
    <span>sighttrue.com &middot; read every 4 hours</span>
  </div>
</body>
</html>
`;

writeFileSync(OUT, banner);
console.log(`banner.html written from the real strip across ${watched} repositories.`);
