/**
 * The mark: a plumb bob that is also a bird's head.
 *
 *   node scripts/build-mark.mjs
 *
 * ## Drawn against a reference
 *
 * Six marks were made and rejected before this one, and every one failed the
 * same way: thin. Single stroke weight, hairlines, shapes outlined rather than
 * filled. Conceptually defensible and visually unfinished — a wireframe, not a
 * logo.
 *
 * The reference the user finally supplied settled it. A logofolio of about
 * eighty marks, and they share four properties without exception:
 *
 *   1. Solid fill. No outlines anywhere, no stroke weights to get wrong.
 *   2. Heavy. Every one survives being printed at the size of a fingernail.
 *   3. One flat colour. Black on paper, and nothing depends on a second.
 *   4. Negative space does a job. The counter is not leftover — it is where the
 *      second reading lives, and it is what separates a logo from a pictogram.
 *
 * ## The shape
 *
 * A single solid form, wide and round at the top, tapering to a point.
 *
 * Read one way it is a plumb bob: the oldest instrument for establishing what is
 * true by measuring it, and the phrase masons still use — plumb and true — is
 * the name of this product. It hangs, and the point either meets the datum or
 * it does not. That is a reading rather than an opinion.
 *
 * Read the other way the punched circle is an eye and the whole form is the head
 * of a bird of prey, which is the other half of the name. Nothing in nature
 * sights better.
 *
 * One object, two readings, and the second one lives in the hole. That is the
 * move the reference makes on nearly every mark in it.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

const X = 32;

/**
 * The cord and its collar, and why the mark would be worthless without them.
 *
 * The first solid version was a round cap tapering to a point with a circle
 * punched in the middle. That is the Google Maps pin — the single most
 * recognised glyph on the internet — and it says "location", which is not what
 * this product does.
 *
 * A pin is dropped. A bob hangs. The cord is the whole difference, and it is
 * also the honest one: a plumb bob without a line is not an instrument, it is a
 * weight. So the line goes in, with a turned collar where it seats, and the cap
 * flattens so the silhouette stops being a circle with a tail.
 */
const CORD_TOP = 3;
const CORD_W = 4.2;
const COLLAR_Y = 12;
const COLLAR_H = 4.4;
const COLLAR_HALF = 9;

/** Where the shoulder sits. Everything above it is the cap. */
const SHOULDER = 30;
/** Half-width. Deliberately fat — this is the property every reference mark shares. */
const HALF = 17.5;
/** The point. Short of the frame so the silhouette has air beneath it. */
const TIP = 57;

/**
 * The eye.
 *
 * Above the shoulder and slightly high in the cap, where an eye sits on a bird
 * rather than in the middle of a face. Centred it read as a washer with a hole
 * in it; three units up and it reads as looking at you.
 *
 * Large. A small counter closes up at 16px and the second reading disappears
 * exactly where a mark needs it most.
 */
const EYE = { y: 28, r: 6.2 };

const r = (n) => Number(n.toFixed(2));

/**
 * The body and the eye as one path, with `evenodd` punching the hole.
 *
 * One path rather than a shape plus a background-coloured circle on top. A
 * circle painted in the page colour stops being a hole the moment the mark is
 * placed on anything else — a sticker, somebody's slide, a dark timeline — and
 * that is the most common way a logo breaks in the wild.
 */
const BODY = [
  // A flattened cap rather than a half circle: a bob is turned on a lathe and
  // is wider than it is tall at the shoulder. The half circle is what made the
  // first version a pin.
  `M ${r(X - HALF)} ${SHOULDER}`,
  `A ${HALF} ${r(HALF * 0.78)} 0 0 1 ${r(X + HALF)} ${SHOULDER}`,
  `L ${X} ${TIP}`,
  'Z',
  `M ${X} ${r(EYE.y - EYE.r)}`,
  `a ${EYE.r} ${EYE.r} 0 1 0 0.01 0`,
  'Z',
].join(' ');

function mark({ ink, alert, title, datum = true }) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64" role="img" aria-label="${title}">
  <title>${title}</title>

  <!--
    A plumb bob that is also the head of a bird of prey. Generated by
    scripts/build-mark.mjs, which records the six marks this replaced and the
    single property they all lacked: weight.

    Solid fill, one flat colour, and the eye is a real hole rather than a circle
    painted in the background colour — a painted counter stops being a hole the
    moment the mark is placed on anything else.
  -->

  <g fill="${ink}">
    <!-- The cord and the collar it seats in. Without these the silhouette is a
         map pin, which says location and not measurement. -->
    <rect x="${r(X - CORD_W / 2)}" y="${CORD_TOP}" width="${CORD_W}" height="${r(COLLAR_Y - CORD_TOP + 1)}" />
    <rect x="${r(X - COLLAR_HALF)}" y="${COLLAR_Y}" width="${r(COLLAR_HALF * 2)}" height="${COLLAR_H}" />
    <path d="${BODY}" fill-rule="evenodd" />
  </g>
${
  datum
    ? `
  <!-- The datum the point is measured against. The only element carrying a
       judgement, so the only one in the alert colour. -->
  <rect x="8" y="61" width="48" height="3" fill="${alert}" />`
    : ''
}
</svg>
`;
}

writeFileSync(
  `${ROOT}assets/brand/mark.svg`,
  mark({ ink: 'currentColor', alert: 'currentColor', title: 'Sighttrue' }),
  'utf8',
);

/**
 * The favicon and the avatar carry their own colours: neither inherits anything
 * from a page, and both are drawn against chrome this project does not control.
 */
writeFileSync(
  `${ROOT}src/site/favicon.svg`,
  mark({ ink: '#d2e2f4', alert: '#f2857c', title: 'Sighttrue' }),
  'utf8',
);

writeFileSync(
  `${ROOT}assets/brand/mark-dark.svg`,
  mark({ ink: '#d2e2f4', alert: '#f2857c', title: 'Sighttrue' }),
  'utf8',
);

writeFileSync(
  `${ROOT}assets/brand/mark-light.svg`,
  mark({ ink: '#1a1a1a', alert: '#a3231b', title: 'Sighttrue' }),
  'utf8',
);

/** Silhouette only, for the avatar tile and anywhere the datum would crowd it. */
writeFileSync(
  `${ROOT}assets/brand/mark-solo.svg`,
  mark({ ink: '#d2e2f4', alert: '#f2857c', title: 'Sighttrue', datum: false }),
  'utf8',
);

console.log('mark.svg, mark-dark.svg, mark-light.svg, mark-solo.svg and favicon.svg written');
