/**
 * One-time bootstrap for `data/watchlist.jsonl`.
 *
 * After this runs, the JSONL file is the source of truth. The watchlist is a
 * committed file, not something generated at runtime, and every change to it is
 * a reviewed commit — the set of repositories being watched is an editorial
 * claim, not configuration. This script therefore refuses to clobber an
 * existing file unless explicitly forced.
 *
 *   node scripts/seed-watchlist.ts
 *   node scripts/seed-watchlist.ts --force
 *
 * The starting set is ~400 repositories across five categories. The budget
 * supports several thousand, so growth from here is an editorial decision
 * rather than a technical one.
 *
 * Names are recorded as GitHub spells them. Any that have since been renamed
 * will answer 404 or redirect on the first real collector run; the collector
 * marks those inactive and continues rather than crashing. Validating them is
 * Prompt 2's job — this script makes no network calls.
 */

import { existsSync } from 'node:fs';
import { WATCHLIST_PATH } from '../src/lib/paths.ts';
import { writeWatchlist } from '../src/lib/ledger.ts';
import type { Category, WatchlistEntry } from '../src/types/watchlist.ts';

const ADDED = '2026-08-04';

const AI_ML = [
  'pytorch/pytorch',
  'tensorflow/tensorflow',
  'huggingface/transformers',
  'huggingface/diffusers',
  'huggingface/datasets',
  'huggingface/accelerate',
  'huggingface/peft',
  'huggingface/tokenizers',
  'huggingface/text-generation-inference',
  'huggingface/trl',
  'huggingface/candle',
  'ggml-org/llama.cpp',
  'ggml-org/whisper.cpp',
  'ollama/ollama',
  'vllm-project/vllm',
  'sgl-project/sglang',
  'langchain-ai/langchain',
  'langchain-ai/langgraph',
  'run-llama/llama_index',
  'openai/openai-python',
  'openai/whisper',
  'openai/tiktoken',
  'anthropics/anthropic-sdk-python',
  'scikit-learn/scikit-learn',
  'keras-team/keras',
  'jax-ml/jax',
  'pytorch/vision',
  'pytorch/audio',
  'ultralytics/ultralytics',
  'facebookresearch/faiss',
  'facebookresearch/detectron2',
  'facebookresearch/segment-anything',
  'facebookresearch/fairseq',
  'open-mmlab/mmdetection',
  'AUTOMATIC1111/stable-diffusion-webui',
  'comfyanonymous/ComfyUI',
  'Stability-AI/stablediffusion',
  'CompVis/stable-diffusion',
  'mlflow/mlflow',
  'ray-project/ray',
  'dask/dask',
  'numpy/numpy',
  'pandas-dev/pandas',
  'scipy/scipy',
  'matplotlib/matplotlib',
  'optuna/optuna',
  'wandb/wandb',
  'onnx/onnx',
  'microsoft/onnxruntime',
  'microsoft/DeepSpeed',
  'microsoft/autogen',
  'NVIDIA/NeMo',
  'NVIDIA/TensorRT',
  'triton-lang/triton',
  'Lightning-AI/pytorch-lightning',
  'Lightning-AI/litgpt',
  'karpathy/nanoGPT',
  'karpathy/llm.c',
  'karpathy/minGPT',
  'meta-llama/llama',
  'meta-llama/llama3',
  'google-research/bert',
  'google-research/google-research',
  'EleutherAI/gpt-neox',
  'EleutherAI/lm-evaluation-harness',
  'axolotl-ai-cloud/axolotl',
  'unslothai/unsloth',
  'mudler/LocalAI',
  'oobabooga/text-generation-webui',
  'deepset-ai/haystack',
  'explosion/spaCy',
  'flairNLP/flair',
  'UKPLab/sentence-transformers',
  'stanfordnlp/dspy',
  'BerriAI/litellm',
  'guidance-ai/guidance',
  'dottxt-ai/outlines',
  'instructor-ai/instructor',
  'mistralai/mistral-inference',
  'QwenLM/Qwen',
];

const WEB_FRAMEWORK = [
  'facebook/react',
  'vuejs/core',
  'angular/angular',
  'sveltejs/svelte',
  'sveltejs/kit',
  'vercel/next.js',
  'nuxt/nuxt',
  'remix-run/react-router',
  'withastro/astro',
  'solidjs/solid',
  'preactjs/preact',
  'emberjs/ember.js',
  'vitejs/vite',
  'webpack/webpack',
  'rollup/rollup',
  'parcel-bundler/parcel',
  'evanw/esbuild',
  'swc-project/swc',
  'expressjs/express',
  'fastify/fastify',
  'koajs/koa',
  'nestjs/nest',
  'hapijs/hapi',
  'honojs/hono',
  'denoland/deno',
  'oven-sh/bun',
  'nodejs/node',
  'django/django',
  'pallets/flask',
  'fastapi/fastapi',
  'encode/starlette',
  'encode/httpx',
  'Pylons/pyramid',
  'tornadoweb/tornado',
  'rails/rails',
  'sinatra/sinatra',
  'hanami/hanami',
  'laravel/laravel',
  'laravel/framework',
  'symfony/symfony',
  'slimphp/Slim',
  'spring-projects/spring-boot',
  'spring-projects/spring-framework',
  'quarkusio/quarkus',
  'micronaut-projects/micronaut-core',
  'playframework/playframework',
  'gin-gonic/gin',
  'labstack/echo',
  'gofiber/fiber',
  'go-chi/chi',
  'beego/beego',
  'actix/actix-web',
  'tokio-rs/axum',
  'rwf2/Rocket',
  'seanmonstar/warp',
  'tokio-rs/tokio',
  'dotnet/aspnetcore',
  'phoenixframework/phoenix',
  'elixir-lang/elixir',
  'vapor/vapor',
  'jquery/jquery',
  'alpinejs/alpine',
  'lit/lit',
  'hotwired/turbo',
  'bigskysoftware/htmx',
  'tailwindlabs/tailwindcss',
  'twbs/bootstrap',
  'mui/material-ui',
  'chakra-ui/chakra-ui',
  'ant-design/ant-design',
  'shadcn-ui/ui',
  'radix-ui/primitives',
  'TanStack/query',
  'TanStack/router',
  'TanStack/table',
  'reduxjs/redux',
  'pmndrs/zustand',
  'mobxjs/mobx',
  'vuejs/pinia',
  'trpc/trpc',
];

const DATABASE = [
  'postgres/postgres',
  'mysql/mysql-server',
  'MariaDB/server',
  'sqlite/sqlite',
  'mongodb/mongo',
  'redis/redis',
  'valkey-io/valkey',
  'apache/cassandra',
  'scylladb/scylladb',
  'elastic/elasticsearch',
  'opensearch-project/OpenSearch',
  'ClickHouse/ClickHouse',
  'duckdb/duckdb',
  'duckdb/duckdb-wasm',
  'cockroachdb/cockroach',
  'yugabyte/yugabyte-db',
  'pingcap/tidb',
  'vitessio/vitess',
  'citusdata/citus',
  'timescale/timescaledb',
  'influxdata/influxdb',
  'questdb/questdb',
  'apache/druid',
  'apache/pinot',
  'neo4j/neo4j',
  'dgraph-io/dgraph',
  'surrealdb/surrealdb',
  'etcd-io/etcd',
  'hashicorp/consul',
  'apache/zookeeper',
  'minio/minio',
  'rqlite/rqlite',
  'supabase/supabase',
  'pocketbase/pocketbase',
  'directus/directus',
  'hasura/graphql-engine',
  'prisma/prisma',
  'drizzle-team/drizzle-orm',
  'typeorm/typeorm',
  'sequelize/sequelize',
  'knex/knex',
  'kysely-org/kysely',
  'sqlalchemy/sqlalchemy',
  'go-gorm/gorm',
  'diesel-rs/diesel',
  'launchbadge/sqlx',
  'jOOQ/jOOQ',
  'mikro-orm/mikro-orm',
  'ent/ent',
  'tursodatabase/libsql',
  'apache/hbase',
  'apache/hive',
  'apache/iceberg',
  'delta-io/delta',
  'apache/hudi',
  'trinodb/trino',
  'prestodb/presto',
  'apache/spark',
  'apache/flink',
  'apache/kafka',
  'redpanda-data/redpanda',
  'nats-io/nats-server',
  'rabbitmq/rabbitmq-server',
  'apache/pulsar',
  'debezium/debezium',
  'dbt-labs/dbt-core',
  'airbytehq/airbyte',
  'apache/airflow',
  'dagster-io/dagster',
  'PrefectHQ/prefect',
  'weaviate/weaviate',
  'milvus-io/milvus',
  'qdrant/qdrant',
  'chroma-core/chroma',
  'pgvector/pgvector',
  'lancedb/lancedb',
  'facebook/rocksdb',
  'google/leveldb',
  'memcached/memcached',
  'tikv/tikv',
];

const DEVTOOL = [
  'microsoft/vscode',
  'neovim/neovim',
  'vim/vim',
  'emacs-mirror/emacs',
  'helix-editor/helix',
  'zed-industries/zed',
  'git/git',
  'cli/cli',
  'desktop/desktop',
  'nvm-sh/nvm',
  'docker/cli',
  'moby/moby',
  'containerd/containerd',
  'kubernetes/kubernetes',
  'helm/helm',
  'kubernetes-sigs/kustomize',
  'argoproj/argo-cd',
  'fluxcd/flux2',
  'hashicorp/terraform',
  'opentofu/opentofu',
  'pulumi/pulumi',
  'ansible/ansible',
  'hashicorp/vagrant',
  'hashicorp/packer',
  'hashicorp/vault',
  'hashicorp/nomad',
  'prometheus/prometheus',
  'grafana/grafana',
  'grafana/loki',
  'open-telemetry/opentelemetry-collector',
  'jaegertracing/jaeger',
  'elastic/kibana',
  'getsentry/sentry',
  'nginx/nginx',
  'caddyserver/caddy',
  'traefik/traefik',
  'envoyproxy/envoy',
  'haproxy/haproxy',
  'curl/curl',
  'httpie/cli',
  'sharkdp/bat',
  'sharkdp/fd',
  'BurntSushi/ripgrep',
  'junegunn/fzf',
  'ajeetdsouza/zoxide',
  'starship/starship',
  'ohmyzsh/ohmyzsh',
  'tmux/tmux',
  'jesseduffield/lazygit',
  'jesseduffield/lazydocker',
  'charmbracelet/bubbletea',
  'charmbracelet/gum',
  'jqlang/jq',
  'mikefarah/yq',
  'eza-community/eza',
  'dandavison/delta',
  'tldr-pages/tldr',
  'astral-sh/ruff',
  'astral-sh/uv',
  'python/mypy',
  'psf/black',
  'pylint-dev/pylint',
  'microsoft/pyright',
  'eslint/eslint',
  'prettier/prettier',
  'biomejs/biome',
  'microsoft/TypeScript',
  'babel/babel',
  'jestjs/jest',
  'vitest-dev/vitest',
  'microsoft/playwright',
  'cypress-io/cypress',
  'puppeteer/puppeteer',
  'nodejs/undici',
  'pnpm/pnpm',
  'yarnpkg/berry',
  'nrwl/nx',
  'vercel/turborepo',
  'renovatebot/renovate',
  'semantic-release/semantic-release',
];

const CRYPTO_WEB3 = [
  'ethereum/go-ethereum',
  'ethereum/solidity',
  'ethereum/EIPs',
  'ethereum/consensus-specs',
  'ethereum/execution-specs',
  'ethereum/py-evm',
  'paradigmxyz/reth',
  'erigontech/erigon',
  'NethermindEth/nethermind',
  'hyperledger/besu',
  'sigp/lighthouse',
  'prysmaticlabs/prysm',
  'ChainSafe/lodestar',
  'status-im/nimbus-eth2',
  'Consensys/teku',
  'bitcoin/bitcoin',
  'bitcoin/bips',
  'lightningnetwork/lnd',
  'ElementsProject/lightning',
  'anza-xyz/agave',
  'solana-labs/solana-web3.js',
  'coral-xyz/anchor',
  'near/nearcore',
  'cosmos/cosmos-sdk',
  'cometbft/cometbft',
  'cosmos/ibc-go',
  'tendermint/tendermint',
  'paritytech/polkadot-sdk',
  'paritytech/subxt',
  'AztecProtocol/aztec-packages',
  'matter-labs/zksync-era',
  'OffchainLabs/nitro',
  'ethereum-optimism/optimism',
  'starkware-libs/cairo',
  'scroll-tech/scroll',
  'base-org/node',
  'OpenZeppelin/openzeppelin-contracts',
  'OpenZeppelin/openzeppelin-contracts-upgradeable',
  'foundry-rs/foundry',
  'NomicFoundation/hardhat',
  'trufflesuite/truffle',
  'ApeWorX/ape',
  'eth-brownie/brownie',
  'ethers-io/ethers.js',
  'wevm/viem',
  'wevm/wagmi',
  'web3/web3.js',
  'ethereum/web3.py',
  'rainbow-me/rainbowkit',
  'WalletConnect/walletconnect-monorepo',
  'safe-global/safe-smart-account',
  'Uniswap/v3-core',
  'Uniswap/v4-core',
  'Uniswap/interface',
  'aave/aave-v3-core',
  'compound-finance/compound-protocol',
  'curvefi/curve-contract',
  'makerdao/dss',
  'balancer/balancer-v2-monorepo',
  'smartcontractkit/chainlink',
  'graphprotocol/graph-node',
  'ipfs/kubo',
  'libp2p/go-libp2p',
  'filecoin-project/lotus',
  'ArweaveTeam/arweave',
  'ceramicnetwork/js-ceramic',
  'MetaMask/metamask-extension',
  'MetaMask/snaps',
  'a16z/helios',
  'bluealloy/revm',
  'alloy-rs/alloy',
  'gakonst/ethers-rs',
  'crytic/slither',
  'crytic/echidna',
  'a16z/halmos',
  'privacy-scaling-explorations/halo2',
  'zkcrypto/bellman',
  'arkworks-rs/algebra',
  'iden3/circom',
  'iden3/snarkjs',
];

const BY_CATEGORY: Record<Category, readonly string[]> = {
  'ai-ml': AI_ML,
  'web-framework': WEB_FRAMEWORK,
  database: DATABASE,
  devtool: DEVTOOL,
  'crypto-web3': CRYPTO_WEB3,
};

function build(): WatchlistEntry[] {
  const entries: WatchlistEntry[] = [];
  const seen = new Map<string, Category>();

  for (const [category, repos] of Object.entries(BY_CATEGORY) as [
    Category,
    readonly string[],
  ][]) {
    for (const id of repos) {
      if (!/^[\w.-]+\/[\w.-]+$/.test(id)) {
        throw new Error(`seed-watchlist: "${id}" is not a valid owner/repo`);
      }

      const key = id.toLowerCase();
      const existing = seen.get(key);
      if (existing) {
        throw new Error(
          `seed-watchlist: "${id}" appears in both ${existing} and ${category}`,
        );
      }
      seen.set(key, category);

      entries.push({ id, category, added: ADDED, active: true });
    }
  }

  return entries;
}

function main(): void {
  const force = process.argv.includes('--force');

  if (existsSync(WATCHLIST_PATH) && !force) {
    console.error(
      'watchlist.jsonl already exists. It is the source of truth once seeded —\n' +
        'edit it directly and commit the change with a reason. Pass --force only\n' +
        'to rebuild from scratch.',
    );
    process.exitCode = 1;
    return;
  }

  const entries = build();
  writeWatchlist(entries);

  const counts = new Map<Category, number>();
  for (const entry of entries) {
    counts.set(entry.category, (counts.get(entry.category) ?? 0) + 1);
  }

  console.log(`wrote ${entries.length} entries to data/watchlist.jsonl`);
  for (const [category, count] of [...counts].sort()) {
    console.log(`  ${category.padEnd(14)} ${String(count).padStart(3)}`);
  }
}

main();
