import { createHash } from 'node:crypto';

import { THEME_BOOT } from './render.ts';

/**
 * `_headers` — what Cloudflare Pages sends with every file.
 *
 * Owed since the audit and deferred while the site was read-only, because on a
 * site with no accounts the worst a missing header costs is a mediocre grade on
 * a scanner. Sign-in changes that. There is now a session cookie worth stealing
 * and a form worth framing, so the deferral is over.
 *
 * Generated rather than hand-written, for one reason: the policy contains the
 * hash of an inline script, and a hash written by hand is a hash that goes
 * stale the first time somebody edits the script it covers — after which the
 * theme flashes on every page load and nobody connects the two.
 */

/**
 * The strict half.
 *
 * `script-src` carries no `'unsafe-inline'`. The site has exactly one inline
 * script — the theme boot, which has to run before the first paint or the page
 * repaints from dark to light in front of somebody who chose light — and it is
 * allowed by hash. That is the header that decides whether an injected string
 * becomes running code, so it is the one worth being strict about.
 *
 * `style-src` does carry `'unsafe-inline'`, and pretending otherwise would be
 * worse than admitting it: 1,650 `style` attributes are emitted across the
 * site, mostly measured widths on prose, and CSP hashes do not cover attributes
 * at all. Removing them is a real change to a lot of templates rather than a
 * header edit, so it is named here as the thing that is not yet true.
 *
 * `connect-src` lists OSV because the stack page queries it from the browser on
 * purpose — a pasted manifest is checked for advisories without ever being sent
 * to this server, which is both the honest architecture and the reason that
 * origin has to be allowed.
 */
function csp(scriptHash: string): string {
  return [
    "default-src 'self'",
    `script-src 'self' 'sha256-${scriptHash}' https://static.cloudflareinsights.com`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "font-src 'self'",
    "connect-src 'self' https://api.osv.dev https://cloudflareinsights.com",
    // Nothing here embeds anything, and nothing here should be embeddable.
    "frame-src 'none'",
    "object-src 'none'",
    // Stops an injected <base> silently repointing every relative URL on the
    // page, including the sign-in link.
    "base-uri 'none'",
    // The sign-out button posts to this origin. Nothing else posts anywhere.
    "form-action 'self'",
    // The modern X-Frame-Options, and the one browsers actually honour now.
    "frame-ancestors 'none'",
    'upgrade-insecure-requests',
  ].join('; ');
}

export function renderHeaders(): string {
  const hash = createHash('sha256').update(THEME_BOOT, 'utf8').digest('base64');

  return `# Generated by the build. Editing this file directly will not survive the
# next deploy — change src/site/headers.ts.
#
# The Content-Security-Policy carries the hash of the one inline script on the
# site, so it is computed here rather than written down. A hash written by hand
# goes stale the first time that script changes, and the symptom is a theme
# flash on every page load that nobody traces back to a header.

/*
  Content-Security-Policy: ${csp(hash)}
  # Two years, and eligible for preload. Every request to this domain is HTTPS
  # already; this is what stops the very first one being downgraded.
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  # Belt and braces with frame-ancestors above, for anything that predates CSP.
  X-Frame-Options: DENY
  # Stops a browser deciding that a .json full of user-supplied names is HTML.
  X-Content-Type-Options: nosniff
  # The path is fine to send — every page here is public and linkable. The query
  # string is not: the stack page puts dependency names in the URL.
  Referrer-Policy: strict-origin-when-cross-origin
  # None of these are used, and a feature that is never requested should not be
  # available to an injected script either.
  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=(), usb=(), interest-cohort=()
  # Removes the cross-origin timing side channels that isolation exists to close.
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin

# Anything about a specific person, never held by a shared cache. The endpoints
# set this themselves; it is repeated here so a new one cannot forget to.
/api/*
  Cache-Control: no-store
  X-Content-Type-Options: nosniff

# The published readings, which is the whole point of the site. Long enough to
# be cheap, short enough that a four-hourly pulse is visible within the hour.
/data/*
  Cache-Control: public, max-age=600, stale-while-revalidate=3600
  Access-Control-Allow-Origin: *

# Immutable by name. These change filename when they change.
/fonts/*
  Cache-Control: public, max-age=31536000, immutable
`;
}
